### ISSUE TITLE
All logging disappears when plugin is loaded

### ISSUE THREAD

**Issue by CompeyDev** [agence-gaya/traefik-plugin-cloudflare#5]
If I load the plugin in my traefik config, all my traefik logs seem to disappear. This does not seem to be affected by the `debug` config option.

**Comment by jliebert** [comment]
Sorry, no idea about your trouble and link to the plugin himself. 
Please provide more information, reproductible traefik setup...

**Comment by CompeyDev** [comment]
**docker-compose.yml**:

```yml
services:
  traefik:
    image: traefik:3.2.2
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./config/traefik/static.yml:/etc/traefik/traefik.yml
      - ./config/traefik/dynamic:/etc/traefik/config
      - ./config/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.example.com`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.api.middlewares=cloudflare'
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.file.directory=/etc/traefik/config'
      - '--providers.file.filename=/etc/traefik/traefik.yml'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--certificatesResolvers.letsencrypt.acme.email=mail@example.com'
      - '--certificatesResolvers.letsencrypt.acme.storage=acme.json'
      - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http'
      - '--log=true'
      - '--log.level=INFO'
      - '--accesslog=true'
      - '--accesslog.format=common'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  public:
    name: public
`````

Static config (**/etc/traefik/traefik.yml**):
```yml
http:
  middlewares:
    cloudflare:
      plugin:
        cloudflare:
          allowedCIDRs:
          	- 10.0.0.0/8
          	- 172.16.0.0/12
          	- 192.168.0.0/16
          overwriteRequestHeader: true
          debug: true

experimental:
  plugins:
    cloudflare:
      moduleName: github.com/agence-gaya/traefik-plugin-cloudflare
      version: v1.2.0
```
