### ISSUE TITLE
Seems allowedCIDR's doesn't work

### ISSUE THREAD

**Issue by fma965** [agence-gaya/traefik-plugin-cloudflare#6]
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: cloudflare-plugin
    namespace: traefik
spec:
    plugin:
        traefik-plugin-cloudflare:
            overwriteRequestHeader: "true"
            refreshInterval: 24h
            debug: "true"
            allowedCIDRs: 
            - 10.0.10.0/24
            - 192.168.1.0/24
```
```
traefik-779b5cf6d6-x2bt5 2025-03-12T21:00:22Z ERR 2025/03/12 21:00:22 debug: deny request from: 192.168.1.10 module=github.com/agence-gaya/traefik-plugin-cloudflare plugin=plugin-traefik-plugin-cloudflare
```
